export type IndexStock = { symbol: string; name: string };

export const INDEX_STOCKS: Record<string, IndexStock[]> = {
  "Dow Jones": [
    { symbol: "AAPL", name: "Apple" },
    { symbol: "AMGN", name: "Amgen" },
    { symbol: "AXP", name: "American Express" },
    { symbol: "BA", name: "Boeing" },
    { symbol: "CAT", name: "Caterpillar" },
    { symbol: "CRM", name: "Salesforce" },
    { symbol: "CSCO", name: "Cisco" },
    { symbol: "CVX", name: "Chevron" },
    { symbol: "DIS", name: "Walt Disney" },
    { symbol: "GS", name: "Goldman Sachs" },
    { symbol: "HD", name: "Home Depot" },
    { symbol: "HON", name: "Honeywell" },
    { symbol: "IBM", name: "IBM" },
    { symbol: "JNJ", name: "Johnson & Johnson" },
    { symbol: "JPM", name: "JPMorgan Chase" },
    { symbol: "KO", name: "Coca-Cola" },
    { symbol: "MCD", name: "McDonald's" },
    { symbol: "MMM", name: "3M" },
    { symbol: "MRK", name: "Merck & Co." },
    { symbol: "MSFT", name: "Microsoft" },
    { symbol: "NKE", name: "Nike" },
    { symbol: "NVDA", name: "Nvidia" },
    { symbol: "PG", name: "Procter & Gamble" },
    { symbol: "SHW", name: "Sherwin-Williams" },
    { symbol: "TRV", name: "Travelers" },
    { symbol: "UNH", name: "UnitedHealth" },
    { symbol: "V", name: "Visa" },
    { symbol: "VZ", name: "Verizon" },
    { symbol: "WBA", name: "Walgreens" },
    { symbol: "WMT", name: "Walmart" },
  ],
  "Nasdaq 100": [
    { symbol: "AAPL", name: "Apple" },
    { symbol: "MSFT", name: "Microsoft" },
    { symbol: "NVDA", name: "Nvidia" },
    { symbol: "AMZN", name: "Amazon" },
    { symbol: "META", name: "Meta Platforms" },
    { symbol: "GOOGL", name: "Alphabet A" },
    { symbol: "GOOG", name: "Alphabet C" },
    { symbol: "TSLA", name: "Tesla" },
    { symbol: "AVGO", name: "Broadcom" },
    { symbol: "COST", name: "Costco" },
    { symbol: "NFLX", name: "Netflix" },
    { symbol: "AMD", name: "AMD" },
    { symbol: "QCOM", name: "Qualcomm" },
    { symbol: "ADBE", name: "Adobe" },
    { symbol: "LIN", name: "Linde" },
    { symbol: "AMGN", name: "Amgen" },
    { symbol: "TXN", name: "Texas Instruments" },
    { symbol: "INTU", name: "Intuit" },
    { symbol: "BKNG", name: "Booking Holdings" },
    { symbol: "PEP", name: "PepsiCo" },
    { symbol: "AMAT", name: "Applied Materials" },
    { symbol: "ISRG", name: "Intuitive Surgical" },
    { symbol: "MU", name: "Micron" },
    { symbol: "AZN", name: "AstraZeneca" },
    { symbol: "ARM", name: "Arm Holdings" },
    { symbol: "HON", name: "Honeywell" },
    { symbol: "VRTX", name: "Vertex Pharma" },
    { symbol: "PANW", name: "Palo Alto Networks" },
    { symbol: "ADI", name: "Analog Devices" },
    { symbol: "REGN", name: "Regeneron" },
    { symbol: "KLAC", name: "KLA Corporation" },
    { symbol: "SBUX", name: "Starbucks" },
    { symbol: "GILD", name: "Gilead Sciences" },
    { symbol: "MDLZ", name: "Mondelez" },
    { symbol: "SNPS", name: "Synopsys" },
    { symbol: "CDNS", name: "Cadence Design" },
    { symbol: "INTC", name: "Intel" },
    { symbol: "LRCX", name: "Lam Research" },
    { symbol: "CEG", name: "Constellation Energy" },
    { symbol: "MELI", name: "MercadoLibre" },
    { symbol: "CTAS", name: "Cintas" },
    { symbol: "ROP", name: "Roper Technologies" },
    { symbol: "MRVL", name: "Marvell Technology" },
    { symbol: "ADP", name: "ADP" },
    { symbol: "WDAY", name: "Workday" },
    { symbol: "NXPI", name: "NXP Semiconductors" },
    { symbol: "MNST", name: "Monster Beverage" },
    { symbol: "PCAR", name: "PACCAR" },
    { symbol: "PAYX", name: "Paychex" },
    { symbol: "FTNT", name: "Fortinet" },
    { symbol: "ROST", name: "Ross Stores" },
    { symbol: "FANG", name: "Diamondback Energy" },
    { symbol: "CPRT", name: "Copart" },
    { symbol: "ADSK", name: "Autodesk" },
    { symbol: "ODFL", name: "Old Dominion Freight" },
    { symbol: "GEHC", name: "GE HealthCare" },
    { symbol: "AEP", name: "American Electric Power" },
    { symbol: "BKR", name: "Baker Hughes" },
    { symbol: "ON", name: "ON Semiconductor" },
    { symbol: "EXC", name: "Exelon" },
    { symbol: "CTSH", name: "Cognizant" },
    { symbol: "VRSK", name: "Verisk Analytics" },
    { symbol: "FAST", name: "Fastenal" },
    { symbol: "DXCM", name: "DexCom" },
    { symbol: "KHC", name: "Kraft Heinz" },
    { symbol: "XEL", name: "Xcel Energy" },
    { symbol: "EA", name: "Electronic Arts" },
    { symbol: "TEAM", name: "Atlassian" },
    { symbol: "IDXX", name: "IDEXX Laboratories" },
    { symbol: "BIIB", name: "Biogen" },
    { symbol: "ZS", name: "Zscaler" },
    { symbol: "ANSS", name: "ANSYS" },
    { symbol: "CSGP", name: "CoStar Group" },
    { symbol: "CCEP", name: "Coca-Cola Europacific" },
    { symbol: "CHTR", name: "Charter Communications" },
    { symbol: "DLTR", name: "Dollar Tree" },
    { symbol: "DDOG", name: "Datadog" },
    { symbol: "CDW", name: "CDW Corporation" },
    { symbol: "CRWD", name: "CrowdStrike" },
    { symbol: "ILMN", name: "Illumina" },
    { symbol: "ABNB", name: "Airbnb" },
    { symbol: "TTD", name: "The Trade Desk" },
    { symbol: "MRNA", name: "Moderna" },
    { symbol: "GFS", name: "GlobalFoundries" },
    { symbol: "PDD", name: "PDD Holdings" },
    { symbol: "MAR", name: "Marriott" },
    { symbol: "CSX", name: "CSX Corporation" },
    { symbol: "ORLY", name: "O'Reilly Automotive" },
    { symbol: "CMCSA", name: "Comcast" },
    { symbol: "ENPH", name: "Enphase Energy" },
    { symbol: "ZM", name: "Zoom" },
    { symbol: "WBD", name: "Warner Bros. Discovery" },
    { symbol: "SIRI", name: "SiriusXM" },
  ],
  "DAX": [
    { symbol: "ADS.DE", name: "Adidas" },
    { symbol: "AIR.DE", name: "Airbus" },
    { symbol: "ALV.DE", name: "Allianz" },
    { symbol: "BAS.DE", name: "BASF" },
    { symbol: "BAYN.DE", name: "Bayer" },
    { symbol: "BEI.DE", name: "Beiersdorf" },
    { symbol: "BMW.DE", name: "BMW" },
    { symbol: "BNR.DE", name: "Brenntag" },
    { symbol: "CBK.DE", name: "Commerzbank" },
    { symbol: "CON.DE", name: "Continental" },
    { symbol: "1COV.DE", name: "Covestro" },
    { symbol: "DHER.DE", name: "Delivery Hero" },
    { symbol: "DBK.DE", name: "Deutsche Bank" },
    { symbol: "DB1.DE", name: "Deutsche Börse" },
    { symbol: "DHL.DE", name: "DHL Group" },
    { symbol: "DTE.DE", name: "Deutsche Telekom" },
    { symbol: "DTG.DE", name: "Daimler Truck" },
    { symbol: "ENR.DE", name: "Siemens Energy" },
    { symbol: "EOAN.DE", name: "E.ON" },
    { symbol: "FRE.DE", name: "Fresenius" },
    { symbol: "HEI.DE", name: "Heidelberg Materials" },
    { symbol: "HEN3.DE", name: "Henkel" },
    { symbol: "HNR1.DE", name: "Hannover Re" },
    { symbol: "IFX.DE", name: "Infineon" },
    { symbol: "MBG.DE", name: "Mercedes-Benz" },
    { symbol: "MRK.DE", name: "Merck KGaA" },
    { symbol: "MTX.DE", name: "MTU Aero Engines" },
    { symbol: "MUV2.DE", name: "Munich Re" },
    { symbol: "P911.DE", name: "Porsche AG" },
    { symbol: "PAH3.DE", name: "Porsche SE" },
    { symbol: "PUM.DE", name: "PUMA" },
    { symbol: "QGEN.DE", name: "QIAGEN" },
    { symbol: "RHM.DE", name: "Rheinmetall" },
    { symbol: "RWE.DE", name: "RWE" },
    { symbol: "SAP.DE", name: "SAP" },
    { symbol: "SHL.DE", name: "Siemens Healthineers" },
    { symbol: "SIE.DE", name: "Siemens" },
    { symbol: "SRT3.DE", name: "Sartorius" },
    { symbol: "SY1.DE", name: "Symrise" },
    { symbol: "VNA.DE", name: "Vonovia" },
    { symbol: "VOW3.DE", name: "Volkswagen" },
  ],
};

export const EXCHANGE_TYPE: Record<string, "us" | "de"> = {
  "Dow Jones": "us",
  "Nasdaq 100": "us",
  "DAX": "de",
};
